### ISSUE TITLE
informative dropout error

### ISSUE THREAD

**Issue by GoodMan0** [bfshi/InfoDrop#14]
When I use resnet+info_dropout in my task, I met the cuda error as below, could you tell me how to fix it or if you had this problem with your environment ?

```
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f5dcaf4c441 in /usr/local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f5dcaf4bd7a in /usr/local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7f5dc3f83652 in /usr/local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7f5dcaf3cce0 in /usr/local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7f5dc0872acb in /usr/local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x1420bb (0x7f5dcb4bd0bb in /usr/local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3c30f4 (0x7f5dcb73e0f4 in /usr/local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3c3141 (0x7f5dcb73e141 in /usr/local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #23: __libc_start_main + 0xf0 (0x7f5dd15c9830 in /lib/x86_64-linux-gnu/libc.so.6)
```

Thanks !

**Comment by bfshi** [comment]
Hi, sorry I never ran into this before. Could you tell me which part of code this error is occurring from?

**Comment by GoodMan0** [comment]
Thanks your reply ! 
`/pytorch/aten/src/THC/THCTensorRandom.cuh:134: int binarySearchForMultinomial(T *, T *, int, T) [with T = float]: block: [86,0,0], thread: [0,3,0/pytorch/aten/src/THC/THCTensorRandom.cuh:134: int binarySearchForMultinomial(T *, T *, int, T) [with T = float]: block: [148] Assertion `THCNumerics<T>::gt(cumdist[size - 1], 0),0` failed.`
As shown above, the error occured from `torch.multinomial`, and I print the input of this function `prob`, find that all zero or nan in some cases  which may cause `torch.multinomial` can not sample correctly. 
I set `drop_rate = 0.1, temperature = 0.03, band_width = 1.0, radius = 3, patch_sampling_num = 9 `, if there any problem?

Thanks !

**Comment by bfshi** [comment]
Hi, the hyperparameters seems right. If there is 0 or nan in `prob`, then maybe the normalization factor is too big or too small? Because the prob needs to be normalized to have a mass of 1.

**Comment by GoodMan0** [comment]
Thanks your reply !

The calculation of distance may has a little problem, when the inforation is estimated by `distance = torch.exp(-distance / distance.mean() / 2 / self.band_width ** 2)  # using mean of distance to normalize`, the normalize often made distance to be -inf and inf, and then  `prob /= prob.sum(dim=(-2, -1), keepdim=True)` made prob to be nan, so the error happened. When I deleted ` / distance.mean()` this normalize process, this error gone. I dont know if this solution is correct and the affect of this normalize in your infodrop strategy. 

Thanks !

**Comment by bfshi** [comment]
Thanks for pointing this out! I think removing the normalization by `distance.mean()` is also ok if you correspondingly adjust other hyperparameters. I add the this normalization only for the ease of tuning hyperparameters. Or another thing you can try is to use `distance / (distance.mean() + 1e-8)` to avoid the division by zero.
